// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    Ant: typeof import('./src/components/Ant.vue')['default']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AsyncComponent: typeof import('./src/components/AsyncComponent.vue')['default']
    Axios: typeof import('./src/components/Axios.vue')['default']
    Child: typeof import('./src/components/Child.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Route: typeof import('./src/components/Route.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Store: typeof import('./src/components/Store.vue')['default']
  }
}

export {}
